naicsmatch = [
            {'NAICS': 111, 'IO': 1, 'desc': 'Farms'},
            {'NAICS': 112, 'IO': 1, 'desc': 'Farms'},
            {'NAICS': 113, 'IO': 2, 'desc': 'Forestry, fishing, and related activities'},
            {'NAICS': 114, 'IO': 2, 'desc': 'Forestry, fishing, and related activities'},
            {'NAICS': 115, 'IO': 2, 'desc': 'Forestry, fishing, and related activities'},
            {'NAICS': 211, 'IO': 3, 'desc': 'Oil and gas extraction'},
            {'NAICS': 212, 'IO': 4, 'desc': 'Mining, except oil and gas'},
            {'NAICS': 213, 'IO': 5, 'desc': 'Support activities for mining'},
            {'NAICS': 221, 'IO': 6, 'desc': 'Utilities'},
            {'NAICS': 23, 'IO': 7, 'desc': 'Construction'},
            {'NAICS': 311, 'IO': 19, 'desc': 'Food and beverage and tobacco products'},
            {'NAICS': 312, 'IO': 19, 'desc': 'Food and beverage and tobacco products'},
            {'NAICS': 313, 'IO': 20, 'desc': 'Textile mills and textile product mills'},
            {'NAICS': 314, 'IO': 20, 'desc': 'Textile mills and textile product mills'},
            {'NAICS': 315, 'IO': 21, 'desc': 'Apparel and leather and allied products'},
            {'NAICS': 316, 'IO': 21, 'desc': 'Apparel and leather and allied products'},
            {'NAICS': 321, 'IO': 8, 'desc': 'Wood products'},
            {'NAICS': 322, 'IO': 22, 'desc': 'Paper products'},
            {'NAICS': 323, 'IO': 23, 'desc': 'Printing and related support activities'},
            {'NAICS': 324, 'IO': 24, 'desc': 'Petroleum and coal products'},
            {'NAICS': 325, 'IO': 25, 'desc': 'Chemical products'},
            {'NAICS': 326, 'IO': 26, 'desc': 'Plastics and rubber products'},
            {'NAICS': 327, 'IO': 9, 'desc': 'Nonmetallic mineral products'},
            {'NAICS': 331, 'IO': 10, 'desc': 'Primary metals'},
            {'NAICS': 332, 'IO': 11, 'desc': 'Fabricated metal products'},
            {'NAICS': 333, 'IO': 12, 'desc': 'Machinery'},
            {'NAICS': 334, 'IO': 13, 'desc': 'Computer and electronic products'},
            {'NAICS': 335, 'IO': 14, 'desc': 'Electrical equipment, appliances, and components'},
            {'NAICS': 3361, 'IO': 15, 'desc': 'Motor vehicles, bodies and trailers, and parts'},
            {'NAICS': 3362, 'IO': 15, 'desc': 'Motor vehicles, bodies and trailers, and parts'},
            {'NAICS': 3363, 'IO': 15, 'desc': 'Motor vehicles, bodies and trailers, and parts'},
            {'NAICS': 3364, 'IO': 16, 'desc': 'Other transportation equipment'},
            {'NAICS': 3365, 'IO': 16, 'desc': 'Other transportation equipment'},
            {'NAICS': 3366, 'IO': 16, 'desc': 'Other transportation equipment'},
            {'NAICS': 3369, 'IO': 16, 'desc': 'Other transportation equipment'},
            {'NAICS': 337, 'IO': 17, 'desc': 'Furniture and related products'},
            {'NAICS': 339, 'IO': 18, 'desc': 'Miscellaneous manufacturing'},
            {'NAICS': 420, 'IO': 27, 'desc': 'Wholesale trade'},
            {'NAICS': 441, 'IO': 28, 'desc': 'Motor vehicle and parts dealers'},
            {'NAICS': 442, 'IO': 31, 'desc': 'Other retail'},
            {'NAICS': 443, 'IO': 31, 'desc': 'Other retail'},
            {'NAICS': 444, 'IO': 31, 'desc': 'Other retail'},
            {'NAICS': 445, 'IO': 29, 'desc': 'Food and beverage stores'},
            {'NAICS': 446, 'IO': 31, 'desc': 'Other retail'},
            {'NAICS': 447, 'IO': 31, 'desc': 'Other retail'},
            {'NAICS': 448, 'IO': 31, 'desc': 'Other retail'},
            {'NAICS': 451, 'IO': 31, 'desc': 'Other retail'},
            {'NAICS': 452, 'IO': 30, 'desc': 'General merchandise stores'},
            {'NAICS': 481, 'IO': 32, 'desc': 'Air transportation'},
            {'NAICS': 482, 'IO': 33, 'desc': 'Rail transportation'},
            {'NAICS': 483, 'IO': 34, 'desc': 'Water transportation'},
            {'NAICS': 484, 'IO': 35, 'desc': 'Truck transportation'},
            {'NAICS': 485, 'IO': 36, 'desc': 'Transit and ground passenger transportation'},
            {'NAICS': 486, 'IO': 37, 'desc': 'Pipeline transportation'},
            {'NAICS': 487, 'IO': 38, 'desc': 'Other transportation and support activities'},
            {'NAICS': 488, 'IO': 38, 'desc': 'Other transportation and support activities'},
            {'NAICS': 492, 'IO': 38, 'desc': 'Other transportation and support activities'},
            {'NAICS': 493, 'IO': 39, 'desc': 'Warehousing and storage'},
            {'NAICS': 511, 'IO': 40, 'desc': 'Publishing industries, except internet (includes software)'},
            {'NAICS': 512, 'IO': 41, 'desc': 'Motion picture and sound recording industries'},
            {'NAICS': 515, 'IO': 42, 'desc': 'Broadcasting and telecommunications'},
            {'NAICS': 517, 'IO': 42, 'desc': 'Broadcasting and telecommunications'},
            {'NAICS': 518, 'IO': 43, 'desc': 'Data processing, internet publishing, and other information services'},
            {'NAICS': 519, 'IO': 43, 'desc': 'Data processing, internet publishing, and other information services'},
            {'NAICS': 521, 'IO': 44, 'desc': 'Federal Reserve banks, credit intermediation, and related activities'},
            {'NAICS': 522, 'IO': 44, 'desc': 'Federal Reserve banks, credit intermediation, and related activities'},
            {'NAICS': 523, 'IO': 45, 'desc': 'Securities, commodity contracts, and investments'},
            {'NAICS': 524, 'IO': 46, 'desc': 'Insurance carriers and related activities'},
            {'NAICS': 525, 'IO': 47, 'desc': 'Funds, trusts, and other financial vehicles'},
            {'NAICS': 5311, 'IO': 48, 'desc': 'Housing'},
            {'NAICS': 5312, 'IO': 49, 'desc': 'Other real estate'},
            {'NAICS': 5313, 'IO': 49, 'desc': 'Other real estate'},
            {'NAICS': 532, 'IO': 50, 'desc': 'Rental and leasing services and lessors of intangible assets'},
            {'NAICS': 533, 'IO': 50, 'desc': 'Rental and leasing services and lessors of intangible assets'},
            {'NAICS': 5411, 'IO': 51, 'desc': 'Legal services'},
            {'NAICS': 5412, 'IO': 53, 'desc': 'Miscellaneous professional, scientific, and technical services'},
            {'NAICS': 5413, 'IO': 53, 'desc': 'Miscellaneous professional, scientific, and technical services'},
            {'NAICS': 5414, 'IO': 53, 'desc': 'Miscellaneous professional, scientific, and technical services'},
            {'NAICS': 5415, 'IO': 52, 'desc': 'Computer systems design and related services'},
            {'NAICS': 541, 'IO': 53, 'desc': 'Miscellaneous professional, scientific, and technical services'},
            {'NAICS': 55, 'IO': 54, 'desc': 'Management of companies and enterprises'},
            {'NAICS': 561, 'IO': 55, 'desc': 'Administrative and support services'},
            {'NAICS': 562, 'IO': 56, 'desc': 'Waste management and remediation services'},
            {'NAICS': 611, 'IO': 57, 'desc': 'Educational services'},
            {'NAICS': 621, 'IO': 58, 'desc': 'Ambulatory health care services'},
            {'NAICS': 622, 'IO': 59, 'desc': 'Hospitals'},
            {'NAICS': 623, 'IO': 60, 'desc': 'Nursing and residential care facilities'},
            {'NAICS': 624, 'IO': 61, 'desc': 'Social assistance'},
            {'NAICS': 711, 'IO': 62, 'desc': 'Performing arts, spectator sports, museums, and related activities'},
            {'NAICS': 712, 'IO': 62, 'desc': 'Performing arts, spectator sports, museums, and related activities'},
            {'NAICS': 713, 'IO': 63, 'desc': 'Amusements, gambling, and recreation industries'},
            {'NAICS': 721, 'IO': 64, 'desc': 'Accommodation'},
            {'NAICS': 722, 'IO': 65, 'desc': 'Food services and drinking places'},
            {'NAICS': 811, 'IO': 66, 'desc': 'Other services, except government'},
            {'NAICS': 812, 'IO': 66, 'desc': 'Other services, except government'},
            {'NAICS': 813, 'IO': 66, 'desc': 'Other services, except government'},
            {'NAICS': 814, 'IO': 66, 'desc': 'Other services, except government'}
            ]

fipsmatch = [
    {'state': 'US', 'fips': 'US'},
    {'state': 'Alabama', 'fips': '01'},
    {'state': 'Alaska', 'fips': '02'},
    {'state': 'Arizona', 'fips': '04'},
    {'state': 'Arkansas', 'fips': '05'},
    {'state': 'California', 'fips': '06'},
    {'state': 'Colorado', 'fips': '08'},
    {'state': 'Connecticut', 'fips': '09'},
    {'state': 'Delaware', 'fips': '10'},
    {'state': 'District of Columbia', 'fips': '11'},
    {'state': 'Florida', 'fips': '12'},
    {'state': 'Georgia', 'fips': '13'},
    {'state': 'Hawaii', 'fips': '15'},
    {'state': 'Idaho', 'fips': '16'},
    {'state': 'Illinois', 'fips': '17'},
    {'state': 'Indiana', 'fips': '18'},
    {'state': 'Iowa', 'fips': '19'},
    {'state': 'Kansas', 'fips': '20'},
    {'state': 'Kentucky', 'fips': '21'},
    {'state': 'Louisiana', 'fips': '22'},
    {'state': 'Maine', 'fips': '23'},
    {'state': 'Maryland', 'fips': '24'},
    {'state': 'Massachusetts', 'fips': '25'},
    {'state': 'Michigan', 'fips': '26'},
    {'state': 'Minnesota', 'fips': '27'},
    {'state': 'Mississippi', 'fips': '28'},
    {'state': 'Missouri', 'fips': '29'},
    {'state': 'Montana', 'fips': '30'},
    {'state': 'Nebraska', 'fips': '31'},
    {'state': 'Nevada', 'fips': '32'},
    {'state': 'New Hampshire', 'fips': '33'},
    {'state': 'New Jersey', 'fips': '34'},
    {'state': 'New Mexico', 'fips': '35'},
    {'state': 'New York', 'fips': '36'},
    {'state': 'North Carolina', 'fips': '37'},
    {'state': 'North Dakota', 'fips': '38'},
    {'state': 'Ohio', 'fips': '39'},
    {'state': 'Oklahoma', 'fips': '40'},
    {'state': 'Oregon', 'fips': '41'},
    {'state': 'Pennsylvania', 'fips': '42'},
    {'state': 'Puerto Rico', 'fips': '72'},
    {'state': 'Rhode Island', 'fips': '44'},
    {'state': 'South Carolina', 'fips': '45'},
    {'state': 'South Dakota', 'fips': '46'},
    {'state': 'Tennessee', 'fips': '47'},
    {'state': 'Texas', 'fips': '48'},
    {'state': 'Utah', 'fips': '49'},
    {'state': 'Vermont', 'fips': '50'},
    {'state': 'Virginia', 'fips': '51'},
    {'state': 'Virgin Islands', 'fips': '78'},
    {'state': 'Washington', 'fips': '53'},
    {'state': 'West Virginia', 'fips': '54'},
    {'state': 'Wisconsin', 'fips': '55'},
    {'state': 'Wyoming', 'fips': '56'}
]

